### ISSUE TITLE
Use git-lfs for test images

### ISSUE THREAD

**Issue by HedgehogCode** [fiji/simplified-io#2]
The test images are large and they should be in git-lfs which would prevent the repository size from growing if the images change.

**Comment by fjug** [comment]
I agree!

**Comment by turekg** [comment]
Curtis suggests sourcing the images off the net like the SCIFIO tests do. I think that's an even better solution. I will work on that and upload any missing test files to https://scif.io/samples where most of those images come from (I suspect the missing ones are the ones I sourced somewhere from BioFormats)

**Comment by turekg** [comment]
In the end, I've opted for the lfs route, can someone test that this is now working correctly? I tried to purge the history as well, but I am not sure that worked.

**Comment by HedgehogCode** [comment]
The images are now saved in lfs.

But I think the purging of the history did not work completely. If I clone the repository with:
```
$ export GIT_LFS_SKIP_SMUDGE=1 && git clone git@github.com:fiji/simplified-io.git
```
The images are not resolved as expected but the repository has still a size of 285MB.

**Comment by turekg** [comment]
Thanx for checking Benny, I'll dig into it some more.

**Comment by turekg** [comment]
OK, I think I've done it this time. Benny can you please check that all is OK now?

**Comment by HedgehogCode** [comment]
It is still the same. How did you try to prune the history?

**Comment by turekg** [comment]
I used git filter-branch --force --index-filter "git rm --cached --ignore-unmatch test-data/*" --prune-empty --tag-name-filter cat -- --all

**Comment by turekg** [comment]
I used the command:
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch test-data/*" --prune-empty --tag-name-filter cat -- --all

**Comment by HedgehogCode** [comment]
It should be *test-images* not *test-data*. E.g.:
```
$ git filter-branch --force --index-filter "git rm --cached --ignore-unmatch test-images/*" --prune-empty --tag-name-filter cat -- --all
```

But this also removes the new lfs images. Maybe they can be added again by changing the last commit with `--amend` or doing a rebase and adding them when they were originally added (because the history is rewritten anyway).

**Comment by turekg** [comment]
No sorry, my typo.... it was test-images all along. I actually deleted 2 of the files by name directly with the same command. And no, it does not delete the current images

**Comment by turekg** [comment]
Or it could be that I am not interpreting the feedback from git correctly, but I don't see any obvious error message

**Comment by HedgehogCode** [comment]
For me the command gives a lot of:
```
[...]
rm 'test-images/mouse-kidney.lif.zip'
rm 'test-images/mri-stack.tif'
rm 'test-images/organ-of-corti.tif'
rm 'test-images/particles.gif'
rm 'test-images/t1-head.tif'
rm 'test-images/t1-rendering.tif'
[...]
Ref 'refs/heads/master' was rewritten
Ref 'refs/remotes/origin/master' was rewritten
WARNING: Ref 'refs/remotes/origin/master' is unchanged
Ref 'refs/tags/simplified-io-1.0.0' was rewritten
Ref 'refs/tags/simplified-io-1.0.1' was rewritten
```

and the test-images folder disappears for every commit (also with the lfs content).

**Comment by vanrichter** [comment]
Sorry it's taken me this long to get back to this. So apparently lfs is not completely free. I've ran out of my transfers quota while messing around with trying to clean up the history, so I will go to back to plan A and implement the storage of the test files on the web as outlined above.

**Comment by turekg** [comment]
Sorry it's taken me this long to get back to this. So apparently lfs is not completely free. I've ran out of my transfers quota while messing around with trying to clean up the history, so I will go to back to plan A and implement the storage of the test files on the web as outlined above.

**Comment by turekg** [comment]
OK, I think I have removed traces of lfs, but I still need to remove the test-images directory from the history as well

**Comment by turekg** [comment]
OK, all done....Tests now download from samples.fiji.sc. Also, testing updated to JUnit5 framework and

**Comment by turekg** [comment]
OK, all done....Tests now download from samples.fiji.sc. Also, testing updated to JUnit5 framework and all image files removed from from history.

**Comment by HedgehogCode** [comment]
There are still at least some image in the history. Try `git checkout 97048dc` and you will find the `test-images` directory with images.
The size of the repository is still 48MB.

**Comment by turekg** [comment]
Argh, I will look at this again.... When I ran bfg there  were some references that it could not clean (the tags of the releases)...

**Comment by turekg** [comment]
OK, I think this time I did it. I didn't seem to have much success with bfg, so I used the index-filter approach.
